version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Ensure NCBI_API_KEY in environment
          command: export NCBI_API_KEY="$NCBI_API_KEY"
      - run:
          name: Run tests
          command: pytest tests/
          environment:
            NCBI_API_KEY: $NCBI_API_KEY

workflows:
  test:
    jobs:
      - build-and-test

