version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Setup NCBI_API_KEY
          command: echo 'export NCBI_API_KEY=$NCBI_API_KEY' >> $BASH_ENV
      - run:
          name: Print NCBI_API_KEY
          command: |
            source $BASH_ENV
            echo "NCBI_API_KEY: $NCBI_API_KEY"
      - run:
          name: Run tests
          command: |
            source $BASH_ENV
            pytest tests/

workflows:
  test:
    jobs:
      - build-and-test

